# Пользователи
## Создать нового пользователя

POST http://localhost:5001/users/register HTTP/1.1
Content-Type: application/json

{
  "email": "keks1000@htmlacademy.ru",
  "name": "Keks1",
  "password": "123456",
  "type": "pro"
}

###

## Авторизовать пользователя

POST http://localhost:5001/users/login HTTP/1.1
Content-Type: application/json

{
  "email": "keks1000@htmlacademy.ru",
  "password": "123456"
}

###

## Проверить токен пользователя
GET http://localhost:5001/users/login HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6Imtla3MxMDAwQGh0bWxhY2FkZW15LnJ1IiwibmFtZSI6Iktla3MxIiwiaWQiOiI2OTM1NjE2NmNhNWJmNWE1OTUyMDgzMmUiLCJpYXQiOjE3NjUyMDg1NzgsImV4cCI6MTc2NTM4MTM3OH0.6ywgK12ZA38FkOTTTCqsRBcv36WQZOTEGycVlZK8Dis

###
